server:
  port: 8761

eureka:
  instance:
    hostname: eureka-server01  #eureka实例的主机名
  client:
    register-with-eureka: true #注册本身到Eureka注册中心
    fetch-registry: true #从Eureka注册中心获取服务的注册信息
    service-url:
      defaultZone: http://eureka-server02:8762/eureka/

spring:
  application:
    name: eureka-server
