server:
  port: 8762
eureka:
  instance:
    hostname: eureka-server02  #eureka实例的主机名
  client:
    register-with-eureka: true #不注册本身到Eureka注册中心
    fetch-registry: true #不从Eureka注册中心获取服务的注册信息
    service-url:
      defaultZone: http://eureka-server01:8761/eureka/
spring:
  application:
    name: eureka-server